/* eslint-disable */
const { PrismaClient, Role, ContentStatus } = require("@prisma/client");
const bcrypt = require("bcryptjs");

const prisma = new PrismaClient();

async function main() {
  console.log("Starting database seed...");

  // 1. Create Superadmin User
  const adminUsername = "jamiila";
  const existingAdmin = await prisma.user.findUnique({ where: { username: adminUsername } });

  const salt = await bcrypt.genSalt(10);
  const passwordHash = await bcrypt.hash("jamiila@janic123", salt);

  if (!existingAdmin) {
    await prisma.user.create({
      data: {
        email: "jamiila@janic.edu.so",
        username: adminUsername,
        passwordHash,
        name: "Dean Jamiila",
        role: Role.ADMIN,
        avatar: "/images/admin-avatar.png",
      },
    });
    console.log("Created superadmin user: jamiila (Dean of CS & IT) (Password: jamiila@janic123)");
  } else {
    await prisma.user.update({
      where: { username: adminUsername },
      data: { passwordHash, role: Role.ADMIN },
    });
    console.log("Updated superadmin credentials.");
  }

  // 2. Seed Student Innovation Projects from JANIC docx
  const projects = [
    {
      title: "Maal Hub",
      slug: "maal-hub",
      category: "Web Platform",
      summary: "MaalHub is a platform that connects investors with small business owners and individuals who have innovative business ideas. Users can present their business ideas or projects on the platform to attract potential funding and investment. The platform helps entrepreneurs turn their ideas into successful and sustainable businesses by connecting them with suitable investors.",
      problem: "Access to early-stage capital and structured investment opportunities is severely limited for aspiring Somali entrepreneurs and micro-business owners.",
      solution: "Users can present their business ideas or projects on the platform to attract potential funding and investment, connecting entrepreneurs with verified investors.",
      technology: "Next.js, TypeScript, Node.js, PostgreSQL, Tailwind CSS, REST APIs",
      innovation: "Smart matching algorithms that align investor risk appetite with startup traction metrics, tailored specifically to local business structures.",
      outcomes: "Connected local small business founders and university innovators with potential angel investors and capital.",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
      heroImage: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1200&q=80",
      demoUrl: "https://maalhub.example.com",
      teamMembers: "Abdi Najiib Artan Osman, Sumaya Anwar Mumin",
      order: 1,
      publishedAt: new Date("2026-01-15T00:00:00Z"),
    },
    {
      title: "Full Brand For LUXREST",
      slug: "full-brand-for-luxrest",
      category: "Branding & Design",
      summary: "Full Brand For LUXREST is a complete branding project developed to create a strong, professional, and consistent visual identity for the company. The brand focuses on building trust, a professional image, and long-term growth.",
      problem: "Emerging hospitality and lifestyle enterprises often lack coherent brand identity, diminishing client trust and market competitiveness.",
      solution: "Development of complete brand identity including logo, color palette, typography, visual elements, brand guidelines, and marketing materials communicating reliability and professionalism.",
      technology: "Figma, Adobe Illustrator, Visual Identity Systems, Typography Architecture",
      innovation: "Modular bilingual design guidelines establishing a recognizable and professional identity for long-term brand equity.",
      outcomes: "Delivered complete visual identity kit, corporate stationary, typography guides, and commercial promotional assets.",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
      heroImage: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80",
      teamMembers: "Maryama Sharif Mohamed, Mandeeq Ibraahim Abdulle, Qamar Abdulahi Adan, Nawaal Maxamed Ali",
      order: 2,
      publishedAt: new Date("2026-01-15T00:00:00Z"),
    },
    {
      title: "Badbaado",
      slug: "badbaado",
      category: "HealthTech",
      summary: "Badbaado is a lightweight, secure, and API-first healthcare coordination platform designed to bridge inter-hospital patient handoffs and deliver advance emergency triage alerts.",
      problem: "Grounded in direct field research with healthcare leaders and former Somalia Doctors Union executive leadership, Badbaado addresses the critical structural disconnect that occurs when patients are transferred between independent healthcare institutions.",
      solution: "Operates as an External Referral & Pre-Arrival Triage Gateway, equipping referring physicians with a frictionless external referral bridge and receiving ERs with triage alerts.",
      technology: "Next.js, FastAPI, WebSockets, Docker, MySQL, Redis, Tailwind CSS",
      innovation: "External Referral & Pre-Arrival Triage Gateway bypassing intrusive EMR unification resistance while securing fast transfer communication.",
      outcomes: "Eliminated transfer coordination delays and enabled advance emergency preparation for incoming trauma cases.",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
      heroImage: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80",
      demoUrl: "https://badbaado-health.example.com",
      teamMembers: "Nawaal Mohamed Ali, Salmo Mohamud Dhuxulow, Aisha Abdirisak Ahmed",
      order: 3,
      publishedAt: new Date("2026-01-15T00:00:00Z"),
    },
    {
      title: "Robot Car Cleaner",
      slug: "robot-car-cleaner",
      category: "Robotics",
      summary: "The Robot Car Cleaner is an Arduino-based robotic vehicle designed to detect and collect waste from the ground using sensors to identify obstacles and navigate surroundings while collecting small pieces of waste.",
      problem: "Manual waste cleaning in workshop and campus grounds is labor-intensive, repetitive, and time-consuming.",
      solution: "Uses sensors to identify obstacles and navigate surroundings while collecting small pieces of waste using a built-in collection mechanism, supporting automated cleaning and reducing manual labor.",
      technology: "Arduino Mega, C++, Ultrasonic Sensors, L298N Motor Driver, 3D CAD Modeling",
      innovation: "Obstacle avoidance sensor integration with low-power sweeping motorized rollers for automated waste pickup.",
      outcomes: "Demonstrated how robotics and Arduino technology can support automated cleaning and improve environmental cleanliness.",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
      heroImage: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1200&q=80",
      videoUrl: "https://youtube.com/watch?v=example-robot",
      teamMembers: "Fardowza Cali Ibraahim, Deeqo C/raxmaan Axmed, Caasho Qaasim Maxamed, Qadiijo C/risaaq Aadan",
      order: 4,
      publishedAt: new Date("2026-01-15T00:00:00Z"),
    },
    {
      title: "Student File",
      slug: "student-file",
      category: "Information Systems",
      summary: "Student File Duplication & Storage Cleaner: A system designed to manage student files and identify duplicate files in order to prevent unnecessary storage usage and improve file management efficiency.",
      problem: "University servers and student repositories accumulate duplicate and redundant files, exhausting storage space and impeding file organization.",
      solution: "Identifies duplicate files within the student file storage system, reduces unnecessary storage usage, makes student file management easier and more efficient, and removes redundant copies.",
      technology: "Python, Next.js, MySQL, SHA-256 Hashing, Storage Optimization, REST APIs",
      innovation: "Automated duplicate detection algorithm tailored for institutional registrar file archives.",
      outcomes: "Simplifies management of student files, reducing storage consumption and minimizing redundant data.",
      status: ContentStatus.PUBLISHED,
      isFeatured: false,
      heroImage: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=80",
      teamMembers: "Juweyriya Mohamed Roble, Khadiija Ahmad Mohamed",
      order: 5,
      publishedAt: new Date("2026-01-15T00:00:00Z"),
    },
    {
      title: "Video Editing",
      slug: "video-editing",
      category: "Digital Media",
      summary: "Documentary of program JANIC: A cinematic documentary chronicling the innovation journey, student projects, research milestones, and institutional vision of JANIC at Jazeera University.",
      problem: "Technological breakthroughs and student incubation achievements require high-quality video production to inspire the public and inform stakeholders.",
      solution: "A multi-part documentary and visual storytelling series showcasing student laboratories, prototype demonstrations, and program milestones.",
      technology: "Adobe Premiere Pro, DaVinci Resolve, Cinema 4K Cameras, Audio Post-Production",
      innovation: "High-definition documentary narrative capturing Somali youth technological empowerment.",
      outcomes: "Completed official showcase documentary screened across university forums and media channels.",
      status: ContentStatus.PUBLISHED,
      isFeatured: false,
      heroImage: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=1200&q=80",
      videoUrl: "https://youtube.com/watch?v=janic-doc",
      teamMembers: "Sumaya Bashir Ali, Abdirisak, Salah Mohamed, Mohamed Abas",
      order: 6,
      publishedAt: new Date("2026-01-15T00:00:00Z"),
    },
    {
      title: "Smart Dust Pin",
      slug: "smart-dust-pin",
      category: "IoT & Hardware",
      summary: "Smart Dust Pin is an Arduino-based smart waste management system designed to automatically detect and separate dry and wet waste using sensors to direct waste into appropriate containers.",
      problem: "Mixed waste in educational facilities contaminates recyclable items and requires tedious manual waste sorting.",
      solution: "Sensors identify the type of waste and direct it into the appropriate container, improving waste sorting, reducing manual effort, and promoting environmental cleanliness.",
      technology: "Arduino, Moisture Sensors, Servo Motors, Proximity Detectors, Embedded C",
      innovation: "Sensor-actuated automated sorting mechanism for immediate separation of organic and recyclable refuse.",
      outcomes: "Automated dry and wet waste separation bin demonstrated on campus grounds.",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
      heroImage: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=1200&q=80",
      teamMembers: "Salmo Mohamud Dhuxulow, Aisha Abdirisak Ahmed",
      order: 7,
      publishedAt: new Date("2026-01-15T00:00:00Z"),
    },
    {
      title: "Bluetooth Controlled Smart Home Automation System",
      slug: "smart-home-automation",
      category: "IoT & Automation",
      summary: "A simple and efficient smart home automation system that allows users to control household electrical devices wirelessly through a mobile application using Bluetooth communication.",
      problem: "Traditional physical switches lack accessibility for elderly or mobility-impaired individuals and provide no centralized wireless control.",
      solution: "Enables users to control household electrical devices wirelessly through a mobile application using Bluetooth communication.",
      technology: "Arduino Uno, HC-05 Bluetooth Module, Relay Modules, Android Studio, Embedded C",
      innovation: "Low-latency wireless command interface connecting smartphone controls with high-voltage household electrical circuits.",
      outcomes: "Constructed functional wireless home automation prototype controlling lights, fans, and appliances with instant mobile response.",
      status: ContentStatus.PUBLISHED,
      isFeatured: false,
      heroImage: "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1200&q=80",
      teamMembers: "Aasiya Ibraahim Ismaaciil, Aamina Nour Abdi",
      order: 8,
      publishedAt: new Date("2026-01-15T00:00:00Z"),
    },
    {
      title: "Smart Child Daily Activity Tracking",
      slug: "smart-child-activity-tracking",
      category: "HealthTech",
      summary: "The Smart Child Daily Activity Tracking System is a modern system designed to record and track children's daily activities, making it easy for parents to manage and follow up on their child's data every day.",
      problem: "Working parents frequently experience difficulty monitoring their young children's daily routines, activity levels, and schedules in real-time.",
      solution: "Records and tracks children's daily activities, providing parents with a clear interface to manage and follow up on their child's data and activities every day.",
      technology: "Flutter, Node.js, Express, MySQL, Mobile Tracking Interfaces",
      innovation: "Parental companion interface featuring daily activity timelines and real-time routine notifications.",
      outcomes: "Developed parent mobile app with intuitive timeline visualization and activity status logging.",
      status: ContentStatus.PUBLISHED,
      isFeatured: false,
      heroImage: "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&w=1200&q=80",
      teamMembers: "Ruweyda Nuur Xusain, Amal Zakaria Cabdulahi, Iman Adam Ali",
      order: 9,
      publishedAt: new Date("2026-01-15T00:00:00Z"),
    },
    {
      title: "JANIC Web Team",
      slug: "janic-web-team",
      category: "Web Platform",
      summary: "Jazeera Nexus Innovation Center (JANIC) is a technology and innovation center at Jazeera University connecting academic knowledge, research, technology, and practical skills to develop real-world solutions.",
      problem: "JANIC required a unified, state-of-the-art digital infrastructure to showcase student innovations, host research archives, facilitate program registrations, and connect with global partners.",
      solution: "Empowers students and professionals through innovation, training, applied research, entrepreneurship, and technology development via an enterprise-grade digital portal.",
      technology: "Next.js 16, React 19, TypeScript, Prisma ORM, MySQL, Tailwind CSS",
      innovation: "Unified hub featuring real-time showcase feeds, dynamic media integration, and administrative program management.",
      outcomes: "Engineered and deployed the production JANIC web platform representing Jazeera University.",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
      heroImage: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80",
      teamMembers: "Abdilahi Abdiweli Adam, Muscab Ahmed Mohamud",
      order: 10,
      publishedAt: new Date("2026-01-15T00:00:00Z"),
    },
    {
      title: "SomaliBDV",
      slug: "somalibdv",
      category: "HealthTech",
      summary: "Somali Blood Donation Volunteers (SomaliBDV) is a digital platform designed to make blood donation coordination easier in Somalia, connecting donors with people who need blood.",
      problem: "Healthcare organizations face severe bottlenecks coordinating blood requests and identifying available donors during medical emergencies.",
      solution: "Connects blood donors with people in need, providing an organized way to register donors and submit and manage blood requests for hospitals and healthcare organizations.",
      technology: "Next.js, Node.js, Express, SMS Notification Gateway, MySQL, Tailwind CSS",
      innovation: "Organized donor-recipient coordination platform optimized for emergency hospital requests in Somalia.",
      outcomes: "Streamlined voluntary donor onboarding and emergency blood request management for regional clinics.",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
      heroImage: "https://images.unsplash.com/photo-1615461066841-6116e61058f4?auto=format&fit=crop&w=1200&q=80",
      teamMembers: "Ismail Ibrahim Abdirahim",
      order: 11,
      publishedAt: new Date("2026-01-15T00:00:00Z"),
    },
    {
      title: "XARIIR",
      slug: "xariir",
      category: "Mobile & Cloud",
      summary: "XARIIR - Real-time Messaging & Social Communication Platform. A full-stack messaging application providing secure, real-time communication with rich media support.",
      problem: "Users require secure, privacy-respecting messaging platforms optimized for varying mobile bandwidth and cross-device synchronization.",
      solution: "Combines robust authentication, rich media sharing (images, videos, files), and social features like status updates, groups, and community building.",
      technology: "React Native, Expo, Node.js, Express, WebSockets, REST APIs, MySQL",
      innovation: "Microservice-inspired architecture using Node.js/Express backend and React Native/Expo mobile clients with real-time WebSocket communication.",
      outcomes: "Seamless cross-platform communication with instant updates, status sharing, and media transfers.",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
      heroImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
      teamMembers: "Muscab Ahmad Mohamud",
      order: 12,
      publishedAt: new Date("2026-01-15T00:00:00Z"),
    },
    {
      title: "Dalag App",
      slug: "dalag-app",
      category: "AgriTech",
      summary: "Dalag App is a mobile app that connects farmers directly to buyers (markets, restaurants, individual customers) without middlemen, featuring instant mobile money (EVC Plus) and market prices.",
      problem: "Farmers in Somalia are underpaid by middlemen and lack direct access to open consumer and commercial markets.",
      solution: "Farmers post crop listings with price and quantity, buyers browse and send purchase requests directly, payment is settled instantly through EVC Plus, and pickup/delivery is coordinated.",
      technology: "React Native, Node.js, Express, EVC Plus Mobile Money, MySQL",
      innovation: "Shows current average market prices for common crops so farmers receive fair compensation without intermediary exploitation.",
      outcomes: "Eliminated middleman commissions and established direct, instant mobile money transactions between farmers and buyers.",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
      heroImage: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1200&q=80",
      teamMembers: "Abdiqaadir Mohamed Hassan",
      order: 13,
      publishedAt: new Date("2026-01-15T00:00:00Z"),
    },
    {
      title: "Fuel Management System",
      slug: "fuel-management-system",
      category: "Enterprise Software",
      summary: "A Fuel Management System is a software application designed to manage and monitor fuel operations efficiently, tracking purchases, sales, stock levels, consumption, and preventing fraud.",
      problem: "Fuel stations and fleet operations face substantial losses from manual record keeping, fuel theft, and absence of real-time inventory monitoring.",
      solution: "Provides real-time inventory monitoring, automated record-keeping, report generation, and user access control to improve accuracy, reduce fuel wastage, and ensure accountability.",
      technology: "C# / .NET, React, MySQL, Analytics Dashboards, REST APIs",
      innovation: "Enables administrators to monitor daily operations, manage fuel stock, analyze consumption patterns, and make informed business decisions.",
      outcomes: "Implemented automated fuel audit logging and variance analysis dashboards for fuel management operations.",
      status: ContentStatus.PUBLISHED,
      isFeatured: false,
      heroImage: "https://images.unsplash.com/photo-1545459720-aac8509eb02c?auto=format&fit=crop&w=1200&q=80",
      teamMembers: "Dheeman Osman Ali",
      order: 14,
      publishedAt: new Date("2026-01-15T00:00:00Z"),
    },
    {
      title: "Auto Water",
      slug: "auto-water",
      category: "IoT & Automation",
      summary: "The Automatic Water Dispenser is an Arduino-based system designed to provide water automatically without requiring physical contact, improving hygiene and preventing water waste.",
      problem: "Manual tap fixtures promote contact contamination and lead to persistent water spillage in public facilities.",
      solution: "When a hand or container is placed underneath the water tube, a sensor detects its presence and activates the water flow, stopping automatically when removed.",
      technology: "Arduino Nano, Infrared Proximity Sensor, 12V Solenoid Valve, Relay Module, Flow Meter",
      innovation: "Contactless hygienic dispensing mechanism designed to improve hygiene, reduce unnecessary water consumption, and provide contactless access.",
      outcomes: "Operational contactless dispenser conserving water and elevating hygiene in communal settings.",
      status: ContentStatus.PUBLISHED,
      isFeatured: false,
      heroImage: "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=1200&q=80",
      teamMembers: "Dheeman Osman Ali",
      order: 15,
      publishedAt: new Date("2026-01-15T00:00:00Z"),
    },
  ];

  // Remove any obsolete projects from previous tests not in the 15 projects list
  const activeSlugs = projects.map((p) => p.slug);
  await prisma.project.deleteMany({
    where: {
      slug: { notIn: activeSlugs },
    },
  });

  for (const projectData of projects) {
    const existing = await prisma.project.findUnique({ where: { slug: projectData.slug } });
    if (!existing) {
      await prisma.project.create({ data: projectData });
    } else {
      await prisma.project.update({ where: { slug: projectData.slug }, data: projectData });
    }
  }
  console.log(`Seeded ${projects.length} innovation projects (10 Groups, 5 Individual).`);

  // 2b. Seed Project Members with Roles, Avatars & Social Links
  const projectMembersSeed = [
    // GROUP ONE: Maal Hub
    {
      name: "Abdi Najiib Artan Osman",
      role: "Lead Full-Stack Engineer",
      projectSlug: "maal-hub",
      department: "Faculty of Computer Science & IT",
      bio: "Software developer passionate about fintech architectures, investment democratization, and building resilient full-stack platforms.",
      avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/abdinajiib",
      linkedin: "https://linkedin.com/in/abdi-najiib",
      twitter: "https://x.com/abdinajiib",
      instagram: "https://instagram.com/abdinajiib",
      facebook: "https://facebook.com/abdinajiib",
      website: "https://maalhub.example.com",
      email: "abdinajiib@janic.edu.so",
      phone: "+252 61 511 2233",
      tags: "FinTech, Next.js, PostgreSQL, TypeScript",
      order: 1,
    },
    {
      name: "Sumaya Anwar Mumin",
      role: "Frontend & UI Architect",
      projectSlug: "maal-hub",
      department: "Faculty of Computer Science & IT",
      bio: "UI/UX enthusiast and frontend specialist designing intuitive financial interfaces for micro-business founders.",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/sumayamumin",
      linkedin: "https://linkedin.com/in/sumaya-mumin",
      twitter: "https://x.com/sumayamumin",
      instagram: "https://instagram.com/sumayamumin",
      facebook: "https://facebook.com/sumayamumin",
      website: "https://maalhub.example.com",
      email: "sumaya.anwar@janic.edu.so",
      phone: "+252 61 522 3344",
      tags: "UI/UX, React, Tailwind CSS, Design Systems",
      order: 2,
    },
    // GROUP TWO: Full Brand For LUXREST
    {
      name: "Maryama Sharif Mohamed",
      role: "Creative Brand Director",
      projectSlug: "full-brand-for-luxrest",
      department: "Faculty of Computer Science & IT",
      bio: "Brand strategist and visual designer crafting compelling corporate identities and long-term brand equity.",
      avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/maryamasharif",
      linkedin: "https://linkedin.com/in/maryama-sharif",
      twitter: "https://x.com/maryamasharif",
      instagram: "https://instagram.com/maryamasharif",
      facebook: "https://facebook.com/maryamasharif",
      website: "https://luxrest.example.com",
      email: "maryama.sharif@janic.edu.so",
      phone: "+252 61 533 4455",
      tags: "Brand Strategy, Typography, Visual Identity",
      order: 1,
    },
    {
      name: "Mandeeq Ibraahim Abdulle",
      role: "Visual Systems Lead",
      projectSlug: "full-brand-for-luxrest",
      department: "Faculty of Computer Science & IT",
      bio: "Digital artist focused on packaging guidelines, color harmonies, and responsive digital asset libraries.",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/mandeeqibrahim",
      linkedin: "https://linkedin.com/in/mandeeq-ibrahim",
      twitter: "https://x.com/mandeeqibrahim",
      instagram: "https://instagram.com/mandeeqibrahim",
      facebook: "https://facebook.com/mandeeqibrahim",
      email: "mandeeq.ibrahim@janic.edu.so",
      tags: "Figma, Illustrator, Packaging, Color Systems",
      order: 2,
    },
    {
      name: "Qamar Abdulahi Adan",
      role: "Marketing Materials Designer",
      projectSlug: "full-brand-for-luxrest",
      department: "Faculty of Computer Science & IT",
      bio: "Graphic designer engineering multi-channel collateral, corporate stationery, and advertising assets.",
      avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/qamaradan",
      linkedin: "https://linkedin.com/in/qamar-adan",
      twitter: "https://x.com/qamaradan",
      instagram: "https://instagram.com/qamaradan",
      facebook: "https://facebook.com/qamaradan",
      email: "qamar.adan@janic.edu.so",
      tags: "Marketing Collateral, Digital Banners, Print Media",
      order: 3,
    },
    {
      name: "Nawaal Maxamed Ali",
      role: "Brand Research Specialist",
      projectSlug: "full-brand-for-luxrest",
      department: "Faculty of Computer Science & IT",
      bio: "Market research analyst translating consumer perceptions into structured brand architecture guidelines.",
      avatar: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/nawaalmaxamed",
      linkedin: "https://linkedin.com/in/nawaal-maxamed",
      twitter: "https://x.com/nawaalmaxamed",
      instagram: "https://instagram.com/nawaalmaxamed",
      facebook: "https://facebook.com/nawaalmaxamed",
      email: "nawaal.maxamed@janic.edu.so",
      tags: "Market Research, Brand Guidelines, User Experience",
      order: 4,
    },
    // GROUP THREE: Badbaado
    {
      name: "Nawaal Mohamed Ali",
      role: "Platform Architect & Health Lead",
      projectSlug: "badbaado",
      department: "Faculty of Computer Science & IT",
      bio: "HealthTech researcher dedicated to solving inter-hospital transfer disconnects and medical telemetry in Somalia.",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/nawaalali",
      linkedin: "https://linkedin.com/in/nawaal-mohamed",
      twitter: "https://x.com/nawaalali",
      instagram: "https://instagram.com/nawaalali",
      facebook: "https://facebook.com/nawaalali",
      website: "https://badbaado-health.example.com",
      email: "nawaal.mohamed@janic.edu.so",
      phone: "+252 61 544 5566",
      tags: "HealthTech, FHIR, API Gateway, Triage",
      order: 1,
    },
    {
      name: "Salmo Mohamud Dhuxulow",
      role: "Backend & Triage Gateway Lead",
      projectSlug: "badbaado",
      department: "Faculty of Computer Science & IT",
      bio: "High-performance backend engineer specializing in asynchronous microservices and low-latency emergency messaging.",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/salmodhuxulow",
      linkedin: "https://linkedin.com/in/salmo-dhuxulow",
      twitter: "https://x.com/salmodhuxulow",
      instagram: "https://instagram.com/salmodhuxulow",
      facebook: "https://facebook.com/salmodhuxulow",
      email: "salmo.dhuxulow@janic.edu.so",
      tags: "FastAPI, Docker, WebSockets, Redis",
      order: 2,
    },
    {
      name: "Aisha Abdirisak Ahmed",
      role: "Emergency Clinical UI Specialist",
      projectSlug: "badbaado",
      department: "Faculty of Computer Science & IT",
      bio: "Frontend developer focused on high-urgency ER triage dashboards and responsive mobile telemetry interfaces.",
      avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/aishaahmed",
      linkedin: "https://linkedin.com/in/aisha-abdirisak",
      twitter: "https://x.com/aishaahmed",
      instagram: "https://instagram.com/aishaahmed",
      facebook: "https://facebook.com/aishaahmed",
      email: "aisha.abdirisak@janic.edu.so",
      tags: "Next.js, Tailwind CSS, Real-Time Dashboards",
      order: 3,
    },
    // GROUP FOUR: Robot Car Cleaner
    {
      name: "Fardowza Cali Ibraahim",
      role: "Robotics & Hardware Team Lead",
      projectSlug: "robot-car-cleaner",
      department: "Faculty of Computer Science & IT",
      bio: "Robotics engineer building autonomous Arduino rovers, sensor telemetry arrays, and automated cleaning mechanics.",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/fardowzacali",
      linkedin: "https://linkedin.com/in/fardowza-cali",
      twitter: "https://x.com/fardowzacali",
      instagram: "https://instagram.com/fardowzacali",
      facebook: "https://facebook.com/fardowzacali",
      email: "fardowza.cali@janic.edu.so",
      phone: "+252 61 555 6677",
      tags: "Robotics, Arduino Mega, C++, Motor Drivers",
      order: 1,
    },
    {
      name: "Deeqo C/raxmaan Axmed",
      role: "Sensors & Embedded Firmware Lead",
      projectSlug: "robot-car-cleaner",
      department: "Faculty of Computer Science & IT",
      bio: "Embedded programmer optimizing obstacle avoidance routines and ultrasonic radar sweeps on microcontroller chips.",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/deeqoaxmed",
      linkedin: "https://linkedin.com/in/deeqo-axmed",
      twitter: "https://x.com/deeqoaxmed",
      instagram: "https://instagram.com/deeqoaxmed",
      facebook: "https://facebook.com/deeqoaxmed",
      email: "deeqo.axmed@janic.edu.so",
      tags: "Ultrasonic, Microcontrollers, Firmware, C++",
      order: 2,
    },
    {
      name: "Caasho Qaasim Maxamed",
      role: "Electrical Circuits & Power Engineer",
      projectSlug: "robot-car-cleaner",
      department: "Faculty of Computer Science & IT",
      bio: "Hardware prototyping engineer responsible for voltage regulation, motor driver isolation, and Li-ion battery longevity.",
      avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/caashoqasim",
      linkedin: "https://linkedin.com/in/caasho-qasim",
      twitter: "https://x.com/caashoqasim",
      instagram: "https://instagram.com/caashoqasim",
      facebook: "https://facebook.com/caashoqasim",
      email: "caasho.qasim@janic.edu.so",
      tags: "Circuits, Power Systems, L298N, Prototyping",
      order: 3,
    },
    {
      name: "Qadiijo C/risaaq Aadan",
      role: "Mechanical Chassis & Debris Mechanism",
      projectSlug: "robot-car-cleaner",
      department: "Faculty of Computer Science & IT",
      bio: "3D CAD designer shaping lightweight aerodynamic robotic frames and motorized debris vacuum sweepers.",
      avatar: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/qadiijoaadan",
      linkedin: "https://linkedin.com/in/qadiijo-aadan",
      twitter: "https://x.com/qadiijoaadan",
      instagram: "https://instagram.com/qadiijoaadan",
      facebook: "https://facebook.com/qadiijoaadan",
      email: "qadiijo.aadan@janic.edu.so",
      tags: "CAD, Chassis Design, Mechanical Engineering",
      order: 4,
    },
    // GROUP FIVE: Student File
    {
      name: "Juweyriya Mohamed Roble",
      role: "Systems Architecture & Algorithm Lead",
      projectSlug: "student-file",
      department: "Faculty of Computer Science & IT",
      bio: "Backend developer engineering cryptographic hashing pipelines and institutional storage optimization algorithms.",
      avatar: "https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/juweyriyaroble",
      linkedin: "https://linkedin.com/in/juweyriya-roble",
      twitter: "https://x.com/juweyriyaroble",
      instagram: "https://instagram.com/juweyriyaroble",
      facebook: "https://facebook.com/juweyriyaroble",
      email: "juweyriya.roble@janic.edu.so",
      tags: "Python, SHA-256, File Systems, Cloud Storage",
      order: 1,
    },
    {
      name: "Khadiija Ahmad Mohamed",
      role: "Database & Admin Dashboard Engineer",
      projectSlug: "student-file",
      department: "Faculty of Computer Science & IT",
      bio: "Full-stack engineer building file management consoles, audit trails, and automated duplicate detection reports.",
      avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/khadiijaahmad",
      linkedin: "https://linkedin.com/in/khadiija-ahmad",
      twitter: "https://x.com/khadiijaahmad",
      instagram: "https://instagram.com/khadiijaahmad",
      facebook: "https://facebook.com/khadiijaahmad",
      email: "khadiija.ahmad@janic.edu.so",
      tags: "Next.js, MySQL, REST APIs, System Administration",
      order: 2,
    },
    // GROUP SIX: Video Editing
    {
      name: "Sumaya Bashir Ali",
      role: "Documentary Director & Producer",
      projectSlug: "video-editing",
      department: "Faculty of Computer Science & IT",
      bio: "Cinematographer and creative director chronicling grassroots Somali technology development and student innovation.",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/sumayabashir",
      linkedin: "https://linkedin.com/in/sumaya-bashir",
      twitter: "https://x.com/sumayabashir",
      instagram: "https://instagram.com/sumayabashir",
      facebook: "https://facebook.com/sumayabashir",
      email: "sumaya.bashir@janic.edu.so",
      tags: "Directing, Cinema Production, Storytelling",
      order: 1,
    },
    {
      name: "Abdirisak",
      role: "Lead Cinematographer & Lighting Director",
      projectSlug: "video-editing",
      department: "Faculty of Computer Science & IT",
      bio: "Visual storyteller capturing 4K lab footage, student inventor interviews, and dynamic project showcases.",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/abdirisak-media",
      linkedin: "https://linkedin.com/in/abdirisak-media",
      twitter: "https://x.com/abdirisak_media",
      instagram: "https://instagram.com/abdirisak_media",
      facebook: "https://facebook.com/abdirisak.media",
      email: "abdirisak@janic.edu.so",
      tags: "4K Cameras, Lighting, Framing, Visual Arts",
      order: 2,
    },
    {
      name: "Salah Mohamed",
      role: "Post-Production & Color Grading Editor",
      projectSlug: "video-editing",
      department: "Faculty of Computer Science & IT",
      bio: "Film editor specialized in DaVinci Resolve color timing, timeline pacing, and high-definition export workflows.",
      avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/salahmohamed",
      linkedin: "https://linkedin.com/in/salah-mohamed",
      twitter: "https://x.com/salahmohamed",
      instagram: "https://instagram.com/salahmohamed",
      facebook: "https://facebook.com/salahmohamed",
      email: "salah.mohamed@janic.edu.so",
      tags: "DaVinci Resolve, Premiere Pro, Color Grading",
      order: 3,
    },
    {
      name: "Mohamed Abas",
      role: "Audio Engineer & Motion Graphics Designer",
      projectSlug: "video-editing",
      department: "Faculty of Computer Science & IT",
      bio: "Sound designer crafting crisp audio mixes, motion titles, and cinematic scoring for institutional media.",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/mohamedabas",
      linkedin: "https://linkedin.com/in/mohamed-abas",
      twitter: "https://x.com/mohamedabas",
      instagram: "https://instagram.com/mohamedabas",
      facebook: "https://facebook.com/mohamedabas",
      email: "mohamed.abas@janic.edu.so",
      tags: "Audio Mixing, Motion Graphics, After Effects",
      order: 4,
    },
    // GROUP SEVEN: Smart Dust Pin
    {
      name: "Salmo Mohamud Dhuxulow",
      role: "IoT Systems & Firmware Architect",
      projectSlug: "smart-dust-pin",
      department: "Faculty of Computer Science & IT",
      bio: "Embedded systems builder programming capacitive moisture and proximity sensors for automated waste classification.",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/salmodhuxulow",
      linkedin: "https://linkedin.com/in/salmo-dhuxulow",
      twitter: "https://x.com/salmodhuxulow",
      instagram: "https://instagram.com/salmodhuxulow",
      facebook: "https://facebook.com/salmodhuxulow",
      email: "salmo.dhuxulow@janic.edu.so",
      tags: "Arduino, IoT, Sensor Processing, Smart Bins",
      order: 1,
    },
    {
      name: "Aisha Abdirisak Ahmed",
      role: "Hardware & Actuator Specialist",
      projectSlug: "smart-dust-pin",
      department: "Faculty of Computer Science & IT",
      bio: "Hardware technician responsible for servo motor flap actuation, bin enclosure assembly, and electronic testing.",
      avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/aishaahmed",
      linkedin: "https://linkedin.com/in/aisha-abdirisak",
      twitter: "https://x.com/aishaahmed",
      instagram: "https://instagram.com/aishaahmed",
      facebook: "https://facebook.com/aishaahmed",
      email: "aisha.abdirisak@janic.edu.so",
      tags: "Servo Motors, Enclosures, Recycling Systems",
      order: 2,
    },
    // GROUP EIGHT: Bluetooth Controlled Smart Home
    {
      name: "Aasiya Ibraahim Ismaaciil",
      role: "Mobile App & Bluetooth Protocol Lead",
      projectSlug: "smart-home-automation",
      department: "Faculty of Computer Science & IT",
      bio: "App developer linking Android smartphone Bluetooth commands with real-time microcontroller automation relays.",
      avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/aasiyaibrahim",
      linkedin: "https://linkedin.com/in/aasiya-ibrahim",
      twitter: "https://x.com/aasiyaibrahim",
      instagram: "https://instagram.com/aasiyaibrahim",
      facebook: "https://facebook.com/aasiyaibrahim",
      email: "aasiya.ibrahim@janic.edu.so",
      tags: "Bluetooth HC-05, Android Studio, Flutter, Smart Home",
      order: 1,
    },
    {
      name: "Aamina Nour Abdi",
      role: "Relay Circuit & Hardware Engineer",
      projectSlug: "smart-home-automation",
      department: "Faculty of Computer Science & IT",
      bio: "Hardware engineer specializing in isolated optocoupler relays, AC mains safety, and low-power microcontroller logic.",
      avatar: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/aaminanour",
      linkedin: "https://linkedin.com/in/aamina-nour",
      twitter: "https://x.com/aaminanour",
      instagram: "https://instagram.com/aaminanour",
      facebook: "https://facebook.com/aaminanour",
      email: "aamina.nour@janic.edu.so",
      tags: "Relays, Circuit Safety, Embedded C, Arduino Uno",
      order: 2,
    },
    // GROUP NINE: Smart Child Daily Activity Tracking
    {
      name: "Ruweyda Nuur Xusain",
      role: "Lead Mobile App Architect",
      projectSlug: "smart-child-activity-tracking",
      department: "Faculty of Computer Science & IT",
      bio: "Cross-platform mobile developer creating intuitive parental dashboards, timeline views, and milestone tracking.",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/ruweydanuur",
      linkedin: "https://linkedin.com/in/ruweyda-nuur",
      twitter: "https://x.com/ruweydanuur",
      instagram: "https://instagram.com/ruweydanuur",
      facebook: "https://facebook.com/ruweydanuur",
      email: "ruweyda.nuur@janic.edu.so",
      tags: "Flutter, Mobile UI, Child Wellness, Real-Time",
      order: 1,
    },
    {
      name: "Amal Zakaria Cabdulahi",
      role: "Backend & Data Sync Engineer",
      projectSlug: "smart-child-activity-tracking",
      department: "Faculty of Computer Science & IT",
      bio: "Backend specialist designing REST APIs, user authorization, and encrypted activity log storage for family users.",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/amalzakaria",
      linkedin: "https://linkedin.com/in/amal-zakaria",
      twitter: "https://x.com/amalzakaria",
      instagram: "https://instagram.com/amalzakaria",
      facebook: "https://facebook.com/amalzakaria",
      email: "amal.zakaria@janic.edu.so",
      tags: "Node.js, Express, MySQL, Cloud Storage",
      order: 2,
    },
    {
      name: "Iman Adam Ali",
      role: "UI/UX & Activity Analytics Lead",
      projectSlug: "smart-child-activity-tracking",
      department: "Faculty of Computer Science & IT",
      bio: "Product designer passionate about child developmental metrics, playful visuals, and parent experience design.",
      avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/imanadam",
      linkedin: "https://linkedin.com/in/iman-adam",
      twitter: "https://x.com/imanadam",
      instagram: "https://instagram.com/imanadam",
      facebook: "https://facebook.com/imanadam",
      email: "iman.adam@janic.edu.so",
      tags: "Figma, User Research, Data Visualizations",
      order: 3,
    },
    // GROUP TEN: JANIC Web Team
    {
      name: "Abdilahi Abdiweli Adam",
      role: "Full-Stack Portal Architect",
      projectSlug: "janic-web-team",
      department: "Faculty of Computer Science & IT",
      bio: "Full-stack engineer building the next-generation digital portal, interactive research repos, and showcase features for JANIC.",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/abdilahiabdiweli",
      linkedin: "https://linkedin.com/in/abdilahi-abdiweli",
      twitter: "https://x.com/abdilahiabdiweli",
      instagram: "https://instagram.com/abdilahiabdiweli",
      facebook: "https://facebook.com/abdilahiabdiweli",
      website: "https://janic.edu.so",
      email: "abdilahi.abdiweli@janic.edu.so",
      phone: "+252 61 566 7788",
      tags: "Next.js 16, React 19, TypeScript, Prisma ORM",
      order: 1,
    },
    {
      name: "Muscab Ahmed Mohamud",
      role: "Frontend & Cloud Infrastructure Engineer",
      projectSlug: "janic-web-team",
      department: "Faculty of Computer Science & IT",
      bio: "Frontend specialist designing rich responsive user interfaces, fluid animations, and administrative CMS modules.",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/muscabahmed",
      linkedin: "https://linkedin.com/in/muscab-ahmed",
      twitter: "https://x.com/muscabahmed",
      instagram: "https://instagram.com/muscabahmed",
      facebook: "https://facebook.com/muscabahmed",
      website: "https://janic.edu.so",
      email: "muscab.ahmed@janic.edu.so",
      phone: "+252 61 577 8899",
      tags: "Tailwind CSS, Radix UI, UI/UX, Performance",
      order: 2,
    },
    // INDIVIDUAL: SomaliBDV
    {
      name: "Ismail Ibrahim Abdirahim",
      role: "Founder & Lead Developer",
      projectSlug: "somalibdv",
      department: "Faculty of Computer Science & IT",
      bio: "Social innovator building digital health coordination tools to connect volunteer blood donors with critical hospital requests in Somalia.",
      avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/ismailibrahim",
      linkedin: "https://linkedin.com/in/ismail-ibrahim",
      twitter: "https://x.com/ismailibrahim",
      instagram: "https://instagram.com/ismailibrahim",
      facebook: "https://facebook.com/ismailibrahim",
      website: "https://somalibdv.example.com",
      email: "ismail.ibrahim@janic.edu.so",
      phone: "+252 61 588 9900",
      tags: "HealthTech, SMS Gateway, Blood Registry, Node.js",
      order: 1,
    },
    // INDIVIDUAL: XARIIR
    {
      name: "Muscab Ahmad Mohamud",
      role: "Lead Mobile Architect & Founder",
      projectSlug: "xariir",
      department: "Faculty of Computer Science & IT",
      bio: "Full-stack mobile engineer designing real-time socket communications, end-to-end media streaming, and modern messaging clients.",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/muscabahmad",
      linkedin: "https://linkedin.com/in/muscab-ahmad",
      twitter: "https://x.com/muscabahmad",
      instagram: "https://instagram.com/muscabahmad",
      facebook: "https://facebook.com/muscabahmad",
      email: "muscab.ahmad@janic.edu.so",
      phone: "+252 61 599 0011",
      tags: "React Native, Expo, WebSockets, Express",
      order: 1,
    },
    // INDIVIDUAL: Dalag App
    {
      name: "Abdiqaadir Mohamed Hassan",
      role: "AgriTech Innovator & Lead Developer",
      projectSlug: "dalag-app",
      department: "Faculty of Computer Science & IT",
      bio: "Agricultural technologist connecting rural Somali farmers directly to urban food markets with transparent pricing and instant EVC Plus payments.",
      avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/abdiqaadirhassan",
      linkedin: "https://linkedin.com/in/abdiqaadir-hassan",
      twitter: "https://x.com/abdiqaadirhassan",
      instagram: "https://instagram.com/abdiqaadirhassan",
      facebook: "https://facebook.com/abdiqaadirhassan",
      email: "abdiqaadir.hassan@janic.edu.so",
      phone: "+252 61 600 1122",
      tags: "AgriTech, React Native, Mobile Money, EVC Plus",
      order: 1,
    },
    // INDIVIDUAL: Fuel Management System
    {
      name: "Dheeman Osman Ali",
      role: "Enterprise Systems Developer",
      projectSlug: "fuel-management-system",
      department: "Faculty of Computer Science & IT",
      bio: "Enterprise software developer creating high-reliability inventory monitoring, automated accounting logs, and fuel variance audit systems.",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/dheemanali",
      linkedin: "https://linkedin.com/in/dheeman-ali",
      twitter: "https://x.com/dheemanali",
      instagram: "https://instagram.com/dheemanali",
      facebook: "https://facebook.com/dheemanali",
      email: "dheeman.ali@janic.edu.so",
      phone: "+252 61 611 2233",
      tags: "C#, .NET, Analytics, MySQL, Auditing",
      order: 1,
    },
    // INDIVIDUAL: Auto Water
    {
      name: "Dheeman Osman Ali",
      role: "Hardware & Automation Engineer",
      projectSlug: "auto-water",
      department: "Faculty of Computer Science & IT",
      bio: "Embedded electronics specialist developing contactless hygienic fluid dispensers and water conservation mechanisms.",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
      github: "https://github.com/dheemanali",
      linkedin: "https://linkedin.com/in/dheeman-ali",
      twitter: "https://x.com/dheemanali",
      instagram: "https://instagram.com/dheemanali",
      facebook: "https://facebook.com/dheemanali",
      email: "dheeman.ali@janic.edu.so",
      phone: "+252 61 611 2233",
      tags: "Arduino Nano, Infrared, Solenoid Valves, IoT",
      order: 2,
    },
  ];

  for (const item of projectMembersSeed) {
    const proj = await prisma.project.findUnique({ where: { slug: item.projectSlug } });
    if (proj) {
      const existing = await prisma.projectMember.findFirst({
        where: { name: item.name, projectId: proj.id },
      });

      const memberPayload = {
        name: item.name,
        role: item.role,
        department: item.department,
        bio: item.bio,
        avatar: item.avatar,
        github: item.github,
        linkedin: item.linkedin,
        twitter: item.twitter,
        instagram: item.instagram,
        facebook: item.facebook,
        website: item.website,
        email: item.email,
        phone: item.phone,
        tags: item.tags,
        order: item.order,
        projectId: proj.id,
        isActive: true,
      };

      if (!existing) {
        await prisma.projectMember.create({ data: memberPayload });
      } else {
        await prisma.projectMember.update({ where: { id: existing.id }, data: memberPayload });
      }
    }
  }
  console.log(`Seeded ${projectMembersSeed.length} project members with social links.`);

  // 3. Seed Training Programs
  const trainingPrograms = [
    {
      title: "Full-Stack Web & Platform Engineering",
      slug: "full-stack-web-engineering",
      category: "Software Engineering",
      summary: "Master modern web development from relational databases to responsive React and Next.js user interfaces.",
      description: "An intensive 12-week program designed for aspiring software engineers. Students learn modern TypeScript, Next.js, relational database architecture with MySQL/PostgreSQL, REST and GraphQL APIs, Docker containers, and automated deployment pipelines.",
      level: "Intermediate",
      duration: "12 Weeks",
      schedule: "Mon & Wed, 4:00 PM – 7:00 PM",
      mode: "On-Campus & Hybrid",
      certification: "JANIC Certified Full-Stack Developer",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
      coverImage: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80",
      maxSeats: 30,
    },
    {
      title: "Robotics, Embedded Systems & IoT",
      slug: "robotics-embedded-systems-iot",
      category: "Emerging Technologies",
      summary: "Hands-on engineering covering microcontrollers, sensor integration, Arduino, ESP32, and automated systems.",
      description: "Gain real-world experience designing electronic circuits, programming Arduino and ESP32 microcontrollers, integrating ultrasonic and optical sensors, motor drivers, and building IoT wireless telemetry pipelines.",
      level: "Beginner to Intermediate",
      duration: "10 Weeks",
      schedule: "Tue & Thu, 3:30 PM – 6:30 PM",
      mode: "On-Campus (Hardware Lab)",
      certification: "JANIC Certified IoT & Robotics Specialist",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
      coverImage: "https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?auto=format&fit=crop&w=800&q=80",
      maxSeats: 25,
    },
    {
      title: "Cybersecurity Defense & Network Infrastructure",
      slug: "cybersecurity-network-infrastructure",
      category: "Cybersecurity",
      summary: "Practical training in ethical hacking, vulnerability assessments, firewall configuration, and SOC fundamentals.",
      description: "Prepare for international security certifications with comprehensive practical labs covering network defense, penetration testing fundamentals, secure Linux server hardening, cryptographic protocols, and incident response.",
      level: "Intermediate",
      duration: "8 Weeks",
      schedule: "Saturdays, 9:00 AM – 3:00 PM",
      mode: "On-Campus",
      certification: "JANIC Network Security Practitioner",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
      coverImage: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
      maxSeats: 25,
    },
    {
      title: "Cloud Computing & DevOps Architecture",
      slug: "cloud-computing-devops",
      category: "Cloud Computing",
      summary: "Build scalable cloud infrastructure with Linux, Docker, CI/CD pipelines, and cloud native architectures.",
      description: "Learn how modern tech enterprises deploy and scale applications. Covers containerization with Docker, reverse proxies with Nginx, continuous integration pipelines, and infrastructure management.",
      level: "Intermediate to Advanced",
      duration: "8 Weeks",
      schedule: "Sun & Tue, 5:00 PM – 7:30 PM",
      mode: "Hybrid",
      certification: "JANIC Certified Cloud Associate",
      status: ContentStatus.PUBLISHED,
      isFeatured: false,
      coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
      maxSeats: 30,
    },
    {
      title: "AI, Machine Learning & Intelligent Automation",
      slug: "ai-machine-learning-automation",
      category: "Emerging Technologies",
      summary: "Explore applied machine learning, computer vision, data analysis with Python, and intelligent agent workflows.",
      description: "Dive into data science and modern AI. Learn Python for numerical analysis, train machine learning classifiers with scikit-learn, build neural networks, and explore real-world computer vision applications.",
      level: "Intermediate",
      duration: "10 Weeks",
      schedule: "Wed & Sat, 4:00 PM – 7:00 PM",
      mode: "On-Campus",
      certification: "JANIC Applied AI Practitioner",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
      coverImage: "https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=800&q=80",
      maxSeats: 25,
    },
    {
      title: "UI/UX & Product Design Masterclass",
      slug: "ui-ux-product-design",
      category: "Digital Design",
      summary: "Transform complex software requirements into intuitive, accessible, and delightful digital user interfaces.",
      description: "Learn user research, wireframing, high-fidelity prototyping in Figma, design systems, design tokens, micro-interactions, and developer handoff workflows.",
      level: "Beginner",
      duration: "6 Weeks",
      schedule: "Mon & Thu, 4:00 PM – 6:30 PM",
      mode: "On-Campus",
      certification: "JANIC Product Design Certificate",
      status: ContentStatus.PUBLISHED,
      isFeatured: false,
      coverImage: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=800&q=80",
      maxSeats: 20,
    },
  ];

  for (const program of trainingPrograms) {
    const existing = await prisma.trainingProgram.findUnique({ where: { slug: program.slug } });
    if (!existing) {
      await prisma.trainingProgram.create({ data: program });
    } else {
      await prisma.trainingProgram.update({ where: { slug: program.slug }, data: program });
    }
  }
  console.log(`Seeded ${trainingPrograms.length} training programs.`);

  // 4. Seed Research Papers
  const researchPapers = [
    {
      title: "Applied Technological Research",
      slug: "applied-technology",
      category: "Applied Research",
      abstract: "Focusing on practical solutions for immediate industrial challenges in the local market.",
      content: "Comprehensive applied research portfolio spanning fintech, healthtech, IoT, and enterprise software. Each project follows a strict market-needs-first methodology ensuring immediate real-world applicability and measurable impact metrics.",
      authors: "JANIC Applied Research Division",
      journalOrConference: "JANIC Research Collection, 2024 – 2025",
      publicationDate: new Date("2024-12-01"),
      pdfUrl: "https://janic.edu.so/research/papers/applied-technology-overview.pdf",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
    },
    {
      title: "Student-Led Innovations",
      slug: "student-innovations",
      category: "Student Research",
      abstract: "Empowering the next generation of researchers to push academic boundaries into the real world.",
      content: "A showcase of undergraduate and postgraduate capstone projects, competitive hackathon winners, and incubation-lab prototypes developed by students under JANIC mentorship. Includes the full portfolio of 18+ student innovations from 2021 to date.",
      authors: "Student Researchers, Faculty of CS & IT, Jazeera University",
      journalOrConference: "JANIC Annual Student Showcase",
      publicationDate: new Date("2025-03-10"),
      pdfUrl: "https://janic.edu.so/research/papers/student-innovations.pdf",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
    },
    {
      title: "Digital Future Transformation",
      slug: "digital-transformation",
      category: "Strategic Research",
      abstract: "Strategic research into AI, Blockchain, and the impact of the 4th Industrial Revolution.",
      content: "Horizon-scanning publication examining emerging technologies, regional digital policy, and the future of higher education. Provides a strategic roadmap for Somali institutions navigating AI, blockchain, smart cities, and post-pandemic digital acceleration.",
      authors: "Eng. Abdullahi Hassan, JANIC Strategy Office",
      journalOrConference: "JANIC Strategic Whitepaper Series",
      publicationDate: new Date("2025-06-01"),
      pdfUrl: "https://janic.edu.so/research/papers/digital-future-transformation.pdf",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
    },
    {
      title: "AI-Driven Emergency Triage and Inter-Hospital Coordination in Resource-Constrained Environments",
      slug: "ai-emergency-triage-inter-hospital-coordination",
      category: "Applied Research",
      abstract: "This paper evaluates the efficacy of an API-centric healthcare dispatch architecture that applies lightweight decision-tree classifiers to triage urgent emergency handoffs across secondary healthcare facilities in Mogadishu.",
      content: "Detailed comparative analysis demonstrating a 48% reduction in transfer latency and improved data fidelity under intermittent 3G connectivity.",
      authors: "Dr. Hassan Omar, Eng. Zakaria Jama, Faculty of Computer Science & IT, Jazeera University",
      journalOrConference: "East African Journal of Medical Informatics & Digital Health (2025)",
      doi: "10.1016/j.eajmidh.2025.04.012",
      publicationDate: new Date("2025-05-15"),
      pdfUrl: "https://janic.edu.so/research/papers/ai-triage-badbaado.pdf",
      status: ContentStatus.PUBLISHED,
      isFeatured: false,
    },
    {
      title: "Edge Robotics for Autonomous Municipal Waste Separation in Arid Coastal Cities",
      slug: "edge-robotics-autonomous-waste-separation",
      category: "Technology Innovation",
      abstract: "Investigates the implementation of low-cost edge sensors coupled with embedded microcontroller architectures to automate the sorting of recyclable dry versus wet municipal waste in high-ambient temperature settings.",
      content: "Experimental trials in educational institutions revealed a 91% sensor accuracy rate under heavy dust environments with zero mechanical failures over 90 days.",
      authors: "Mustafa Dahir, Eng. Amina Farah, JANIC Robotics Division",
      journalOrConference: "IEEE International Conference on Sustainable Computing & IoT (2025)",
      doi: "10.1109/ICSCI.2025.1084219",
      publicationDate: new Date("2025-08-20"),
      pdfUrl: "https://janic.edu.so/research/papers/smart-waste-robotics.pdf",
      status: ContentStatus.PUBLISHED,
      isFeatured: false,
    },
    {
      title: "Optimized File Deduplication Architectures for Distributed Academic Information Systems",
      slug: "optimized-file-deduplication-academic-systems",
      category: "Student Research",
      abstract: "Presents an algorithmic framework integrating cryptographic chunk hashing with metadata clustering to minimize institutional cloud storage costs across university faculties.",
      content: "Achieved a 42% physical footprint reduction without degrading latency for simultaneous student download requests during exam cycles.",
      authors: "Ayan Warsame, Dr. Mohamed Qasim",
      journalOrConference: "JANIC Academic Working Papers Series, Vol. 3",
      publicationDate: new Date("2025-11-10"),
      pdfUrl: "https://janic.edu.so/research/papers/academic-deduplication.pdf",
      status: ContentStatus.PUBLISHED,
      isFeatured: false,
    },
  ];

  for (const paper of researchPapers) {
    const existing = await prisma.researchPaper.findUnique({ where: { slug: paper.slug } });
    if (!existing) {
      await prisma.researchPaper.create({ data: paper });
    } else {
      await prisma.researchPaper.update({ where: { slug: paper.slug }, data: paper });
    }
  }
  console.log(`Seeded ${researchPapers.length} research papers.`);

  // 5. Seed Events
  const events = [
    {
      title: "JANIC Innovation Summit 2024",
      slug: "janic-innovation-summit-2024",
      category: "Innovation Showcase",
      summary: "The flagship annual summit bringing together academia, industry, and government leaders to showcase Somali technological innovation.",
      description: "Join university leaders, tech industry pioneers, angel investors, and government representatives as JANIC's student innovators pitch and demonstrate functional prototypes. Featuring keynote speakers from regional tech ecosystems and live startup demos.",
      eventDate: new Date("2026-10-18T09:00:00Z"),
      endDate: new Date("2026-10-18T17:00:00Z"),
      location: "Main Campus Auditorium",
      isVirtual: false,
      capacity: 350,
      registrationUrl: "https://janic.edu.so/events/summit-2024/register",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
      coverImage: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80",
    },
    {
      title: "Cybersecurity Challenge 4.0",
      slug: "cybersecurity-challenge-4",
      category: "Technology Competitions",
      summary: "Capture-the-flag (CTF) cybersecurity tournament testing defensive and offensive security skills across student teams.",
      description: "Fourth edition of the JANIC cybersecurity challenge. Teams compete in network reconnaissance, web exploitation, cryptography, and incident response scenarios. Top teams win certification and direct internship opportunities with JANIC's industry partners.",
      eventDate: new Date("2026-11-04T08:00:00Z"),
      endDate: new Date("2026-11-04T18:00:00Z"),
      location: "Tech Lab B-02",
      isVirtual: false,
      capacity: 80,
      registrationUrl: "https://janic.edu.so/events/cyber-4/register",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
      coverImage: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
    },
    {
      title: "AI Workshop for Developers",
      slug: "ai-workshop-for-developers",
      category: "Workshops & Training",
      summary: "Hands-on workshop covering modern AI integration, LLM APIs, retrieval-augmented generation, and prompt engineering for developers.",
      description: "Practical one-day workshop for software developers. Learn to integrate commercial and open-source LLM APIs, build RAG pipelines, design effective prompts, and deploy AI-powered features into real web applications.",
      eventDate: new Date("2026-12-15T13:30:00Z"),
      endDate: new Date("2026-12-15T18:00:00Z"),
      location: "Hybrid / Online",
      isVirtual: true,
      capacity: 120,
      registrationUrl: "https://janic.edu.so/events/ai-dev-workshop/register",
      status: ContentStatus.PUBLISHED,
      isFeatured: true,
      coverImage: "https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=800&q=80",
    },
    {
      title: "JANIC Annual Tech Showcase & Demo Day 2026",
      slug: "janic-annual-tech-showcase-2026",
      category: "Innovation Showcase",
      summary: "Experience the latest student-built hardware prototypes, AI applications, and startup innovations live on stage.",
      description: "Join university leaders, tech industry pioneers, angel investors, and government representatives as JANIC's student innovators pitch and demonstrate functional prototypes built over the past academic year.",
      eventDate: new Date("2026-11-20T09:00:00Z"),
      endDate: new Date("2026-11-20T17:00:00Z"),
      location: "Jazeera University Main Auditorium, Mogadishu",
      isVirtual: false,
      capacity: 350,
      registrationUrl: "https://janic.edu.so/events/demo-day-2026/register",
      status: ContentStatus.PUBLISHED,
      isFeatured: false,
      coverImage: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=800&q=80",
    },
    {
      title: "Mogadishu Smart Cities Student Hackathon 2026",
      slug: "mogadishu-smart-cities-hackathon-2026",
      category: "Student Hackathons",
      summary: "48-hour competitive hackathon solving urban mobility, healthcare, and digital finance challenges.",
      description: "Teams of 3 to 5 students will collaborate intensively over 48 hours with expert engineering mentors to prototype software and IoT solutions that tackle pressing challenges in urban living.",
      eventDate: new Date("2026-12-05T08:00:00Z"),
      endDate: new Date("2026-12-07T18:00:00Z"),
      location: "JANIC Innovation Lab, Jazeera University",
      isVirtual: false,
      capacity: 120,
      registrationUrl: "https://janic.edu.so/events/smart-cities-hackathon/register",
      status: ContentStatus.PUBLISHED,
      isFeatured: false,
      coverImage: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80",
    },
    {
      title: "Embedded Robotics & IoT Hands-On Workshop",
      slug: "embedded-robotics-iot-workshop",
      category: "Technology Competitions",
      summary: "Interactive microcontroller programming and sensor integration workshop for university and high school tech talents.",
      description: "Learn how to wire, program, and debug Arduino and ESP32 microcontrollers. Attendees build a line-tracking sensor robot from scratch during this intensive weekend workshop.",
      eventDate: new Date("2026-10-25T13:30:00Z"),
      endDate: new Date("2026-10-25T18:00:00Z"),
      location: "JANIC Hardware & Robotics Laboratory",
      isVirtual: false,
      capacity: 50,
      status: ContentStatus.PUBLISHED,
      isFeatured: false,
      coverImage: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
    },
  ];

  for (const event of events) {
    const existing = await prisma.event.findUnique({ where: { slug: event.slug } });
    if (!existing) {
      await prisma.event.create({ data: event });
    } else {
      await prisma.event.update({ where: { slug: event.slug }, data: event });
    }
  }
  console.log(`Seeded ${events.length} events.`);

  // 6. Seed Team Members
  const teamMembers = [
    {
      name: "Jamila Hassan Mohamed",
      role: "CS & IT Dean",
      department: "Faculty of Computer Science & IT, Jazeera University",
      bio: "Visionary founder of JANIC and Dean of the Faculty of Computer Science & IT, leading academic innovation, faculty mentorship, and youth technological empowerment.",
      avatar: "/images/Founder-img.jpeg",
      email: "jamiila@janic.edu.so",
      order: 0,
      isActive: true,
      isFounder: true,
    },
  ];

  for (const member of teamMembers) {
    const existing = await prisma.teamMember.findFirst({ where: { name: member.name } });
    if (!existing) {
      await prisma.teamMember.create({ data: member });
    } else {
      await prisma.teamMember.update({ where: { id: existing.id }, data: member });
    }
  }
  console.log(`Seeded ${teamMembers.length} team members.`);

  // 7. Site Settings
  const settings = [
    { key: "site_name", value: "Jazeera Nexus Innovation Center (JANIC)", group: "general" },
    { key: "site_tagline", value: "Innovating Technology. Empowering the Future.", group: "general" },
    { key: "portal_notice", value: "Official Innovation Hub of the Faculty of Computer Science & IT", group: "general" },
    { key: "institution_name", value: "Jazeera University", group: "general" },
    { key: "faculty_name", value: "Faculty of Computer Science & IT", group: "general" },
    { key: "contact_email", value: "info@janic.edu.so", group: "contact" },
    { key: "contact_phone", value: "+252 61 555 1234", group: "contact" },
    { key: "campus_address", value: "Jazeera University Main Campus, KM4, Mogadishu, Somalia", group: "contact" },
    { key: "founded_date", value: "October 25, 2021", group: "institutional" },
    { key: "linkedin_url", value: "https://linkedin.com/school/jazeera-university", group: "social" },
    { key: "github_url", value: "https://github.com/janic-innovation", group: "social" },
    { key: "twitter_url", value: "", group: "social" },
    { key: "facebook_url", value: "", group: "social" },
    { key: "hero_title", value: "Innovating Technology. Empowering the Future.", group: "hero" },
    { key: "hero_subtitle", value: "The leading institutional hub for technological transformation, advanced research, and digital excellence.", group: "hero" },
    { key: "hero_image", value: "/images/janic-hero-lab.jpg", group: "hero" },
    { key: "hero_badge_value", value: "18+", group: "hero" },
    { key: "hero_badge_label", value: "STUDENT INNOVATION PROJECTS", group: "hero" },
    { key: "footer_tagline", value: "Technology • Innovation • Research • Training", group: "footer" },
    { key: "accreditation_badge", value: "Accredited Academic Innovation Lab", group: "footer" },
    { key: "nav_links", value: "", group: "navigation" },
    { key: "maintenance_mode", value: "false", group: "system" },
    { key: "allow_registrations", value: "true", group: "system" },
    { key: "allow_submissions", value: "true", group: "system" },
    { key: "allow_contact_form", value: "true", group: "system" },
    { key: "featured_count", value: "3", group: "system" },
    {
      key: "role_permissions",
      value: JSON.stringify({
        ADMIN: ["manage_users", "manage_settings", "edit_content", "publish_content", "delete_content", "review_submissions", "manage_media", "manage_team"],
        EDITOR: ["edit_content", "publish_content", "review_submissions", "manage_media"],
        STAFF: ["review_submissions"],
      }),
      group: "permissions",
    },
  ];

  for (const s of settings) {
    await prisma.siteSetting.upsert({
      where: { key: s.key },
      update: { value: s.value, group: s.group },
      create: s,
    });
  }
  console.log("Seeded site settings.");

  console.log("Database seed completed successfully!");
}

main()
  .catch((e) => {
    console.error("Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
